services:
  caddy:
    cap_add:
      - NET_ADMIN
    image: $CONTAINER_REGISTRY/your-org-caddy:latest
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    env_file:
      - ./.env.prod
    environment:
      - DISABLE_VITE_DEV_SERVER=#
    volumes:
      - ./config:/etc/caddy/
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

  tasktap-monolith:
    image: $CONTAINER_REGISTRY/your-org-tasktap-monolith:latest
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    memswap_limit: 2G
    volumes:
      - /opt/tasktap/cron:/app/tasktap/service/cron/data
      - /opt/tasktap/db:/app/tasktap/service/db/data
      - /opt/tasktap/identity:/app/tasktap/service/identity/data
      - /opt/tasktap/identity-http:/app/saflib/identity/identity-http/data

    build:
      context: ../..
      dockerfile: tasktap/service/monolith/Dockerfile

    env_file:
      - ./.env.prod

  prometheus:
    image: prom/prometheus:v2.46.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  loki:
    image: grafana/loki:latest
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
    command: -config.file=/etc/loki/loki-config.yaml

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_storage:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true

  node_exporter:
    image: prom/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($|/)"

volumes:
  caddy_data:
  caddy_config:
  grafana_storage:
